engines:
  rubocop:
    enabled: true
  phpcodesniffer:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Identical code:
        enabled: false
    config:
      languages:
      - php:
ratings:
  paths:
  - "**.php"
exclude_paths:
- "**/vendor/**/*"
- bootstrap/**
- config/**
- node_modules/**
- public/**
- storage/**
- tests/**
- vendor/**/*"
- app/Exceptions/**

