engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    Identical code:
        enabled: false
    config:
      languages:
      - php:
ratings:
  paths:
  - app/**
exclude_paths:
- "**/vendor/**/*"
- bootstrap/**
- config/**
- node_modules/**
- public/**
- resources/**
- routes/**
- storage/**
- tests/**
- vendor/**/*"
- app/Exceptions/**
- app/Providers/**
- app/Http/Middleware/**

