engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true 	
  duplication:
    enabled: false
    config:
      languages:
      - php:
ratings:
  paths:
  - "**.php"
exclude_paths:
- "**/vendor/**/*"
- bootstrap/**
- config/**
- node_modules/**
- public/**
- storage/**
- tests/**
- vendor/**/*"
- app/Exceptions/**
- app/Providers/**
- resources/assets/**
- resources/lang/**
